include: package:flutter_lints/flutter.yaml

# This make flutter suggest const wherever possible
linter:
  rules:
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true